baseURL: "https://raditian-hugo.radity.com/"
languageCode: en-us
theme: raditian-free-hugo-theme-master
params:
  plugins:
    css:
      - URL: css/main.css
      - URL: css/rad-icons.css
      - URL: css/custom.css
    js:
      - URL: js/rad-animations.js
      - URL: js/sticky-header.js
      - URL: js/library/fontfaceobserver.js
  sections:
    - showcase
    - about
    - education
    - experience
    - client-and-work
    - testimonial
    - contact
    - newsletter
  googleTagManagerID: GTM-000000
  logo:
    text1: Andreas
    text2: Ellure
  footer:
    copyright: © Raditian. All rights reserved.
    radity_logo:
      x: img/general/design-and-code-radity.png
      _2x: img/general/design-and-code-radity@2x.png
      alt: Design & Code - Radity
menu:
  header:
    - name: Despre
      URL: "#about"
      weight: 2
    - name: Portofoliu
      URL: "#portfolio"
      weight: 3
    - name: Contact
      URL: "#contact"
      weight: 4
  footer:
    - name: Despre
      URL: "#about"
      weight: 2
    - name: Portofoliu
      URL: "#portfolio"
      weight: 3
    - name: Contact
      URL: "#contact"
      weight: 4
